import AboutMeta from "./AboutMeta";
import AboutTags from "./AboutTags";
import styles from "@/styles/AboutCompany.module.css";
export type AboutCompany = {
  Symbol: string;
  AssetType: string;
  Name: string;
  Description: string;
  Exchange: string;
  Currency: string;
  Country: string;
  Sector: string;
  Industry: string;
  Address: string;
  FullTimeEmployees: string;
  FiscalYearEnd: string;
  LatestQuarter: string;
  MarketCapitalization: string;
  EBITDA: string;
  PERatio: string;
  PEGRatio: string;
  BookValue: string;
  DividendPerShare: string;
  DividendYield: string;
  EPS: string;
  RevenuePerShareTTM: string;
  ProfitMargin: string;
  OperatingMarginTTM: string;
  ReturnOnAssetsTTM: string;
  ReturnOnEquityTTM: string;
  RevenueTTM: string;
  GrossProfitTTM: string;
  DilutedEPSTTM: string;
  QuarterlyEarningsGrowthYOY: string;
  QuarterlyRevenueGrowthYOY: string;
  AnalystTargetPrice: string;
  TrailingPE: string;
  ForwardPE: string;
  PriceToSalesRatioTTM: string;
  PriceToBookRatio: string;
  EVToRevenue: string;
  EVToEBITDA: string;
  Beta: string;
  "52WeekHigh": string;
  "52WeekLow": string;
  "50DayMovingAverage": string;
  "200DayMovingAverage": string;
  SharesOutstanding: string;
  SharesFloat: string;
  SharesShort: string;
};

type AboutCompanyProps = {
  company?: AboutCompany;
  logo?: string;
};
const AboutCompany = ({ company, logo }: AboutCompanyProps) => {
  return (
    <div className={styles.container}>
      <div className={styles.header}>About {company?.Name} IBM</div>
      <div>
        <div className={styles.compDesc}>
          {/* <p>{company.Description}</p> */}
          <p>
            International Business Machines Corporation (IBM) is an American
            multinational technology company headquartered in Armonk, New York,
            with operations in over 170 countries. The company began in 1911,
            founded in Endicott, New York, as the Computing-Tabulating-Recording
            Company (CTR) and was renamed International Business Machines in
            1924. IBM is incorporated in New York. IBM produces and sells
            computer hardware, middleware and software, and provides hosting and
            consulting services in areas ranging from mainframe computers to
            nanotechnology. IBM is also a major research organization, holding
            the record for most annual U.S. patents generated by a business (as
            of 2020) for 28 consecutive years. Inventions by IBM include the
            automated teller machine (ATM), the floppy disk, the hard disk
            drive, the magnetic stripe card, the relational database, the SQL
            programming language, the UPC barcode, and dynamic random-access
            memory (DRAM). The IBM mainframe, exemplified by the System/360, was
            the dominant computing platform during the 1960s and 1970s.
          </p>
        </div>
        <div className={styles.compTags}>
          <AboutTags lable="Industry" tags="Consumer Electronics" />
          <AboutTags lable="Founded" tags="April 1, 1976" />
        </div>
        <div className={styles.priceLimitContainer}>
          <div className={styles.priceLimit}>
            <p>53-Weeks High</p>
            <p className={styles.pricePoint}>$ 151</p>
          </div>
          <div className={styles.priceLimit}>
            <p>53-Weeks Low</p>
            <p className={styles.pricePoint}>$ 118.71</p>
          </div>
        </div>
        <div className={styles.compMeta}>
          <AboutMeta
            label="MarketCapitalization"
            value={company?.MarketCapitalization ?? "$1.5T"}
          />
          <AboutMeta
            label="EVToRevenue"
            value={company?.EVToRevenue ?? "2.969"}
          />
          <AboutMeta label="P/E Ratio" value={company?.PERatio ?? "18.39"} />
        </div>
      </div>
    </div>
  );
};

export default AboutCompany;
